-- db.sql
CREATE DATABASE IF NOT EXISTS `restaurant_stock` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `restaurant_stock`;


-- Basic helpers
CREATE TABLE IF NOT EXISTS units (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
symbol VARCHAR(20) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS suppliers (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
phone VARCHAR(50) DEFAULT NULL,
address VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB;


-- Inventory objects
CREATE TABLE IF NOT EXISTS raw_materials (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
unit_id INT NOT NULL,
opening_qty DECIMAL(18,3) DEFAULT 0,
current_qty DECIMAL(18,3) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (unit_id) REFERENCES units(id)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS products (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
unit_id INT NOT NULL,
opening_qty DECIMAL(18,3) DEFAULT 0,
current_qty DECIMAL(18,3) DEFAULT 0,
selling_price DECIMAL(18,2) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (unit_id) REFERENCES units(id)
) ENGINE=InnoDB;


-- GRN
CREATE TABLE IF NOT EXISTS grns (
id INT AUTO_INCREMENT PRIMARY KEY,
grn_no VARCHAR(50) NOT NULL UNIQUE,
supplier_id INT NOT NULL,
grn_date DATE NOT NULL,
notes VARCHAR(255) DEFAULT NULL,
total_cost DECIMAL(18,2) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS grn_items (
id INT AUTO_INCREMENT PRIMARY KEY,
grn_id INT NOT NULL,
raw_material_id INT NOT NULL,
qty DECIMAL(18,3) NOT NULL,
unit_cost DECIMAL(18,3) NOT NULL,
total_cost DECIMAL(18,3) NOT NULL,
FOREIGN KEY (grn_id) REFERENCES grns(id) ON DELETE CASCADE,
FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id)
) ENGINE=InnoDB;


-- Recipes
CREATE TABLE IF NOT EXISTS recipes (
id INT AUTO_INCREMENT PRIMARY KEY,
product_id INT NOT NULL,
name VARCHAR(150) NOT NULL,
yield_qty DECIMAL(18,3) NOT NULL,
notes VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS recipe_items (
id INT AUTO_INCREMENT PRIMARY KEY,
recipe_id INT NOT NULL,
raw_material_id INT NOT NULL,
qty DECIMAL(18,3) NOT NULL,
FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
FOREIGN KEY (raw_material_id) REFERENCES raw_materials(id)
) ENGINE=InnoDB;


-- Production
CREATE TABLE IF NOT EXISTS productions (
id INT AUTO_INCREMENT PRIMARY KEY,
) ENGINE=InnoDB;

-- Stock ledger (raw + product)
CREATE TABLE IF NOT EXISTS stock_ledger (
id INT AUTO_INCREMENT PRIMARY KEY,
item_type ENUM('raw','product') NOT NULL,
item_id INT NOT NULL,
ref_type ENUM('OPENING','GRN','PROD_CONS','PROD_OUT','ADJUST') NOT NULL,
ref_id INT NULL,
entry_date DATETIME NOT NULL,
qty_in DECIMAL(18,3) DEFAULT 0,
qty_out DECIMAL(18,3) DEFAULT 0,
balance_after DECIMAL(18,3) DEFAULT 0,
note VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB;